server:
  port: 8086
  servlet:
    context-path: /

spring:
  messages:
    basename: messages/response-messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/main
    username: "root"
    password: "0000"